export const FETCH_TAREAS = 'fetchTareas'
export const INSERT_TAREAS = 'insertTareas'
export const FETCH_TAREASESTADO = 'fetchTareasEstado'
export const DELETE_TAREAS = 'deleteTareas'
export const FETCH_DATOS ='fetchDatos'